version: '3.8'

services:
  backend:
    build: ./backend
    container_name: express-backend
    restart: unless-stopped
    ports:
      - 5001:5001
    networks:
      - nodejs-network

  nginx:
    build: ./frontend
    container_name: react
    restart: unless-stopped
    ports:
      - 80:80

    depends_on:
      - backend
    networks:
      - nodejs-network

networks:
  nodejs-network:
    driver: bridge